import pytest


@pytest.fixture
def mock_all_pulls():
    data = {'success': True, 'data': [
        {
            "url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/50",
            "id": 937063858,
            "node_id": "PR_kwDOHUgvcM432nWy",
            "html_url": "https://github.com/RoodrigoRoot/flat-backend-test/pull/50",
            "diff_url": "https://github.com/RoodrigoRoot/flat-backend-test/pull/50.diff",
            "patch_url": "https://github.com/RoodrigoRoot/flat-backend-test/pull/50.patch",
            "issue_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/50",
            "number": 50,
            "state": "closed",
            "locked": False,
            "title": "Docs/readme v2",
            "user": {
                "login": "RoodrigoRoot",
                "id": 50676016,
                "node_id": "MDQ6VXNlcjUwNjc2MDE2",
                "avatar_url": "https://avatars.githubusercontent.com/u/50676016?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/RoodrigoRoot",
                "html_url": "https://github.com/RoodrigoRoot",
                "followers_url": "https://api.github.com/users/RoodrigoRoot/followers",
                "following_url": "https://api.github.com/users/RoodrigoRoot/following{/other_user}",
                "gists_url": "https://api.github.com/users/RoodrigoRoot/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/RoodrigoRoot/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/RoodrigoRoot/subscriptions",
                "organizations_url": "https://api.github.com/users/RoodrigoRoot/orgs",
                "repos_url": "https://api.github.com/users/RoodrigoRoot/repos",
                "events_url": "https://api.github.com/users/RoodrigoRoot/events{/privacy}",
                "received_events_url": "https://api.github.com/users/RoodrigoRoot/received_events",
                "type": "User",
                "site_admin": False
            },
            "body": None,
            "created_at": "2022-05-16T06:01:23Z",
            "updated_at": "2022-05-16T06:01:28Z",
            "closed_at": "2022-05-16T06:01:28Z",
            "merged_at": "2022-05-16T06:01:28Z",
            "merge_commit_sha": "113446b77e491aadd665ba56b0df96a86630e78d",
            "assignee": None,
            "assignees": [],
            "requested_reviewers": [],
            "requested_teams": [],
            "labels": [],
            "milestone": None,
            "draft": False,
            "commits_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/50/commits",
            "review_comments_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/50/comments",
            "review_comment_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/comments{/number}",
            "comments_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/50/comments",
            "statuses_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/statuses/92672a4afab2efc9fa5f948c81844a415ad4a22e",
            "head": {
                "label": "RoodrigoRoot:docs/readme_v2",
                "ref": "docs/readme_v2",
                "sha": "92672a4afab2efc9fa5f948c81844a415ad4a22e",
                "user": {
                    "login": "RoodrigoRoot",
                    "id": 50676016,
                    "node_id": "MDQ6VXNlcjUwNjc2MDE2",
                    "avatar_url": "https://avatars.githubusercontent.com/u/50676016?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/RoodrigoRoot",
                    "html_url": "https://github.com/RoodrigoRoot",
                    "followers_url": "https://api.github.com/users/RoodrigoRoot/followers",
                    "following_url": "https://api.github.com/users/RoodrigoRoot/following{/other_user}",
                    "gists_url": "https://api.github.com/users/RoodrigoRoot/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/RoodrigoRoot/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/RoodrigoRoot/subscriptions",
                    "organizations_url": "https://api.github.com/users/RoodrigoRoot/orgs",
                    "repos_url": "https://api.github.com/users/RoodrigoRoot/repos",
                    "events_url": "https://api.github.com/users/RoodrigoRoot/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/RoodrigoRoot/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "repo": {
                    "id": 491270000,
                    "node_id": "R_kgDOHUgvcA",
                    "name": "flat-backend-test",
                    "full_name": "RoodrigoRoot/flat-backend-test",
                    "private": False,
                    "owner": {
                        "login": "RoodrigoRoot",
                        "id": 50676016,
                        "node_id": "MDQ6VXNlcjUwNjc2MDE2",
                        "avatar_url": "https://avatars.githubusercontent.com/u/50676016?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/RoodrigoRoot",
                        "html_url": "https://github.com/RoodrigoRoot",
                        "followers_url": "https://api.github.com/users/RoodrigoRoot/followers",
                        "following_url": "https://api.github.com/users/RoodrigoRoot/following{/other_user}",
                        "gists_url": "https://api.github.com/users/RoodrigoRoot/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/RoodrigoRoot/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/RoodrigoRoot/subscriptions",
                        "organizations_url": "https://api.github.com/users/RoodrigoRoot/orgs",
                        "repos_url": "https://api.github.com/users/RoodrigoRoot/repos",
                        "events_url": "https://api.github.com/users/RoodrigoRoot/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/RoodrigoRoot/received_events",
                        "type": "User",
                        "site_admin": False
                    },
                    "html_url": "https://github.com/RoodrigoRoot/flat-backend-test",
                    "description": None,
                    "fork": False,
                    "url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test",
                    "forks_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/forks",
                    "keys_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/keys{/key_id}",
                    "collaborators_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/collaborators{/collaborator}",
                    "teams_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/teams",
                    "hooks_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/hooks",
                    "issue_events_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/events{/number}",
                    "events_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/events",
                    "assignees_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/assignees{/user}",
                    "branches_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/branches{/branch}",
                    "tags_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/tags",
                    "blobs_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/blobs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/tags{/sha}",
                    "git_refs_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/refs{/sha}",
                    "trees_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/trees{/sha}",
                    "statuses_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/statuses/{sha}",
                    "languages_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/languages",
                    "stargazers_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/stargazers",
                    "contributors_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/contributors",
                    "subscribers_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/subscribers",
                    "subscription_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/subscription",
                    "commits_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/commits{/sha}",
                    "git_commits_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/commits{/sha}",
                    "comments_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/comments{/number}",
                    "issue_comment_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/comments{/number}",
                    "contents_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/contents/{+path}",
                    "compare_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/compare/{base}...{head}",
                    "merges_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/merges",
                    "archive_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/{archive_format}{/ref}",
                    "downloads_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/downloads",
                    "issues_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues{/number}",
                    "pulls_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls{/number}",
                    "milestones_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/milestones{/number}",
                    "notifications_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/notifications{?since,all,participating}",
                    "labels_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/labels{/name}",
                    "releases_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/releases{/id}",
                    "deployments_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/deployments",
                    "created_at": "2022-05-11T20:57:39Z",
                    "updated_at": "2022-05-12T13:56:05Z",
                    "pushed_at": "2022-05-16T06:01:28Z",
                    "git_url": "git://github.com/RoodrigoRoot/flat-backend-test.git",
                    "ssh_url": "git@github.com:RoodrigoRoot/flat-backend-test.git",
                    "clone_url": "https://github.com/RoodrigoRoot/flat-backend-test.git",
                    "svn_url": "https://github.com/RoodrigoRoot/flat-backend-test",
                    "homepage": None,
                    "size": 26,
                    "stargazers_count": 0,
                    "watchers_count": 0,
                    "language": "Python",
                    "has_issues": True,
                    "has_projects": True,
                    "has_downloads": True,
                    "has_wiki": True,
                    "has_pages": False,
                    "forks_count": 0,
                    "mirror_url": None,
                    "archived": False,
                    "disabled": False,
                    "open_issues_count": 0,
                    "license": None,
                    "allow_forking": True,
                    "is_template": False,
                    "topics": [],
                    "visibility": "public",
                    "forks": 0,
                    "open_issues": 0,
                    "watchers": 0,
                    "default_branch": "main"
                }
            },
            "base": {
                "label": "RoodrigoRoot:main",
                "ref": "main",
                "sha": "e6b105e4b37a97227a3e91801ae6192684507648",
                "user": {
                    "login": "RoodrigoRoot",
                    "id": 50676016,
                    "node_id": "MDQ6VXNlcjUwNjc2MDE2",
                    "avatar_url": "https://avatars.githubusercontent.com/u/50676016?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/RoodrigoRoot",
                    "html_url": "https://github.com/RoodrigoRoot",
                    "followers_url": "https://api.github.com/users/RoodrigoRoot/followers",
                    "following_url": "https://api.github.com/users/RoodrigoRoot/following{/other_user}",
                    "gists_url": "https://api.github.com/users/RoodrigoRoot/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/RoodrigoRoot/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/RoodrigoRoot/subscriptions",
                    "organizations_url": "https://api.github.com/users/RoodrigoRoot/orgs",
                    "repos_url": "https://api.github.com/users/RoodrigoRoot/repos",
                    "events_url": "https://api.github.com/users/RoodrigoRoot/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/RoodrigoRoot/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "repo": {
                    "id": 491270000,
                    "node_id": "R_kgDOHUgvcA",
                    "name": "flat-backend-test",
                    "full_name": "RoodrigoRoot/flat-backend-test",
                    "private": False,
                    "owner": {
                        "login": "RoodrigoRoot",
                        "id": 50676016,
                        "node_id": "MDQ6VXNlcjUwNjc2MDE2",
                        "avatar_url": "https://avatars.githubusercontent.com/u/50676016?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/RoodrigoRoot",
                        "html_url": "https://github.com/RoodrigoRoot",
                        "followers_url": "https://api.github.com/users/RoodrigoRoot/followers",
                        "following_url": "https://api.github.com/users/RoodrigoRoot/following{/other_user}",
                        "gists_url": "https://api.github.com/users/RoodrigoRoot/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/RoodrigoRoot/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/RoodrigoRoot/subscriptions",
                        "organizations_url": "https://api.github.com/users/RoodrigoRoot/orgs",
                        "repos_url": "https://api.github.com/users/RoodrigoRoot/repos",
                        "events_url": "https://api.github.com/users/RoodrigoRoot/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/RoodrigoRoot/received_events",
                        "type": "User",
                        "site_admin": False
                    },
                    "html_url": "https://github.com/RoodrigoRoot/flat-backend-test",
                    "description": None,
                    "fork": False,
                    "url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test",
                    "forks_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/forks",
                    "keys_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/keys{/key_id}",
                    "collaborators_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/collaborators{/collaborator}",
                    "teams_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/teams",
                    "hooks_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/hooks",
                    "issue_events_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/events{/number}",
                    "events_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/events",
                    "assignees_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/assignees{/user}",
                    "branches_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/branches{/branch}",
                    "tags_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/tags",
                    "blobs_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/blobs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/tags{/sha}",
                    "git_refs_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/refs{/sha}",
                    "trees_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/trees{/sha}",
                    "statuses_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/statuses/{sha}",
                    "languages_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/languages",
                    "stargazers_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/stargazers",
                    "contributors_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/contributors",
                    "subscribers_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/subscribers",
                    "subscription_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/subscription",
                    "commits_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/commits{/sha}",
                    "git_commits_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/commits{/sha}",
                    "comments_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/comments{/number}",
                    "issue_comment_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/comments{/number}",
                    "contents_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/contents/{+path}",
                    "compare_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/compare/{base}...{head}",
                    "merges_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/merges",
                    "archive_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/{archive_format}{/ref}",
                    "downloads_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/downloads",
                    "issues_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues{/number}",
                    "pulls_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls{/number}",
                    "milestones_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/milestones{/number}",
                    "notifications_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/notifications{?since,all,participating}",
                    "labels_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/labels{/name}",
                    "releases_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/releases{/id}",
                    "deployments_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/deployments",
                    "created_at": "2022-05-11T20:57:39Z",
                    "updated_at": "2022-05-12T13:56:05Z",
                    "pushed_at": "2022-05-16T06:01:28Z",
                    "git_url": "git://github.com/RoodrigoRoot/flat-backend-test.git",
                    "ssh_url": "git@github.com:RoodrigoRoot/flat-backend-test.git",
                    "clone_url": "https://github.com/RoodrigoRoot/flat-backend-test.git",
                    "svn_url": "https://github.com/RoodrigoRoot/flat-backend-test",
                    "homepage": None,
                    "size": 26,
                    "stargazers_count": 0,
                    "watchers_count": 0,
                    "language": "Python",
                    "has_issues": True,
                    "has_projects": True,
                    "has_downloads": True,
                    "has_wiki": True,
                    "has_pages": False,
                    "forks_count": 0,
                    "mirror_url": None,
                    "archived": False,
                    "disabled": False,
                    "open_issues_count": 0,
                    "license": None,
                    "allow_forking": True,
                    "is_template": False,
                    "topics": [],
                    "visibility": "public",
                    "forks": 0,
                    "open_issues": 0,
                    "watchers": 0,
                    "default_branch": "main"
                }
            },
            "_links": {
                "self": {
                    "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/50"
                },
                "html": {
                    "href": "https://github.com/RoodrigoRoot/flat-backend-test/pull/50"
                },
                "issue": {
                    "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/50"
                },
                "comments": {
                    "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/50/comments"
                },
                "review_comments": {
                    "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/50/comments"
                },
                "review_comment": {
                    "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/comments{/number}"
                },
                "commits": {
                    "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/50/commits"
                },
                "statuses": {
                    "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/statuses/92672a4afab2efc9fa5f948c81844a415ad4a22e"
                }
            },
            "author_association": "OWNER",
            "auto_merge": None,
            "active_lock_reason": None
        }]}
    return data


@pytest.fixture
def mock_details_pull():
    data = {'success': True, 'data': {
        "url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/46",
        "id": 937048301,
        "node_id": "PR_kwDOHUgvcM432jjt",
        "html_url": "https://github.com/RoodrigoRoot/flat-backend-test/pull/46",
        "diff_url": "https://github.com/RoodrigoRoot/flat-backend-test/pull/46.diff",
        "patch_url": "https://github.com/RoodrigoRoot/flat-backend-test/pull/46.patch",
        "issue_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/46",
        "number": 46,
        "state": "closed",
        "locked": False,
        "title": "Prueba de pull request",
        "user": {
            "login": "RoodrigoRoot",
            "id": 50676016,
            "node_id": "MDQ6VXNlcjUwNjc2MDE2",
            "avatar_url": "https://avatars.githubusercontent.com/u/50676016?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/RoodrigoRoot",
            "html_url": "https://github.com/RoodrigoRoot",
            "followers_url": "https://api.github.com/users/RoodrigoRoot/followers",
            "following_url": "https://api.github.com/users/RoodrigoRoot/following{/other_user}",
            "gists_url": "https://api.github.com/users/RoodrigoRoot/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/RoodrigoRoot/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/RoodrigoRoot/subscriptions",
            "organizations_url": "https://api.github.com/users/RoodrigoRoot/orgs",
            "repos_url": "https://api.github.com/users/RoodrigoRoot/repos",
            "events_url": "https://api.github.com/users/RoodrigoRoot/events{/privacy}",
            "received_events_url": "https://api.github.com/users/RoodrigoRoot/received_events",
            "type": "User",
            "site_admin": False
        },
        "body": "Esta es una prueba para crear un pull request",
        "created_at": "2022-05-16T05:30:36Z",
        "updated_at": "2022-05-16T05:31:23Z",
        "closed_at": "2022-05-16T05:31:23Z",
        "merged_at": None,
        "merge_commit_sha": "1573ec523d9b376e163417a707f6fe463fe2c078",
        "assignee": None,
        "assignees": [],
        "requested_reviewers": [],
        "requested_teams": [],
        "labels": [],
        "milestone": None,
        "draft": False,
        "commits_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/46/commits",
        "review_comments_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/46/comments",
        "review_comment_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/comments{/number}",
        "comments_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/46/comments",
        "statuses_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/statuses/b5c5b678aad30675bc5ca22d02b7a62ca9d202c8",
        "head": {
            "label": "RoodrigoRoot:branch_d6ba",
            "ref": "branch_d6ba",
            "sha": "b5c5b678aad30675bc5ca22d02b7a62ca9d202c8",
            "user": {
                "login": "RoodrigoRoot",
                "id": 50676016,
                "node_id": "MDQ6VXNlcjUwNjc2MDE2",
                "avatar_url": "https://avatars.githubusercontent.com/u/50676016?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/RoodrigoRoot",
                "html_url": "https://github.com/RoodrigoRoot",
                "followers_url": "https://api.github.com/users/RoodrigoRoot/followers",
                "following_url": "https://api.github.com/users/RoodrigoRoot/following{/other_user}",
                "gists_url": "https://api.github.com/users/RoodrigoRoot/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/RoodrigoRoot/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/RoodrigoRoot/subscriptions",
                "organizations_url": "https://api.github.com/users/RoodrigoRoot/orgs",
                "repos_url": "https://api.github.com/users/RoodrigoRoot/repos",
                "events_url": "https://api.github.com/users/RoodrigoRoot/events{/privacy}",
                "received_events_url": "https://api.github.com/users/RoodrigoRoot/received_events",
                "type": "User",
                "site_admin": False
            },
            "repo": {
                "id": 491270000,
                "node_id": "R_kgDOHUgvcA",
                "name": "flat-backend-test",
                "full_name": "RoodrigoRoot/flat-backend-test",
                "private": False,
                "owner": {
                    "login": "RoodrigoRoot",
                    "id": 50676016,
                    "node_id": "MDQ6VXNlcjUwNjc2MDE2",
                    "avatar_url": "https://avatars.githubusercontent.com/u/50676016?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/RoodrigoRoot",
                    "html_url": "https://github.com/RoodrigoRoot",
                    "followers_url": "https://api.github.com/users/RoodrigoRoot/followers",
                    "following_url": "https://api.github.com/users/RoodrigoRoot/following{/other_user}",
                    "gists_url": "https://api.github.com/users/RoodrigoRoot/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/RoodrigoRoot/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/RoodrigoRoot/subscriptions",
                    "organizations_url": "https://api.github.com/users/RoodrigoRoot/orgs",
                    "repos_url": "https://api.github.com/users/RoodrigoRoot/repos",
                    "events_url": "https://api.github.com/users/RoodrigoRoot/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/RoodrigoRoot/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "html_url": "https://github.com/RoodrigoRoot/flat-backend-test",
                "description": None,
                "fork": False,
                "url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test",
                "forks_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/forks",
                "keys_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/teams",
                "hooks_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/hooks",
                "issue_events_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/events{/number}",
                "events_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/events",
                "assignees_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/assignees{/user}",
                "branches_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/branches{/branch}",
                "tags_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/tags",
                "blobs_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/languages",
                "stargazers_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/stargazers",
                "contributors_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/contributors",
                "subscribers_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/subscribers",
                "subscription_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/subscription",
                "commits_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/contents/{+path}",
                "compare_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/merges",
                "archive_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/downloads",
                "issues_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues{/number}",
                "pulls_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/labels{/name}",
                "releases_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/releases{/id}",
                "deployments_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/deployments",
                "created_at": "2022-05-11T20:57:39Z",
                "updated_at": "2022-05-12T13:56:05Z",
                "pushed_at": "2022-05-16T06:01:28Z",
                "git_url": "git://github.com/RoodrigoRoot/flat-backend-test.git",
                "ssh_url": "git@github.com:RoodrigoRoot/flat-backend-test.git",
                "clone_url": "https://github.com/RoodrigoRoot/flat-backend-test.git",
                "svn_url": "https://github.com/RoodrigoRoot/flat-backend-test",
                "homepage": None,
                "size": 26,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": "Python",
                "has_issues": True,
                "has_projects": True,
                "has_downloads": True,
                "has_wiki": True,
                "has_pages": False,
                "forks_count": 0,
                "mirror_url": None,
                "archived": False,
                "disabled": False,
                "open_issues_count": 0,
                "license": None,
                "allow_forking": True,
                "is_template": False,
                "topics": [],
                "visibility": "public",
                "forks": 0,
                "open_issues": 0,
                "watchers": 0,
                "default_branch": "main"
            }
        },
        "base": {
            "label": "RoodrigoRoot:test/pull",
            "ref": "test/pull",
            "sha": "88c9a220170575d2e0d8913cd4ef7d7afe3b1274",
            "user": {
                "login": "RoodrigoRoot",
                "id": 50676016,
                "node_id": "MDQ6VXNlcjUwNjc2MDE2",
                "avatar_url": "https://avatars.githubusercontent.com/u/50676016?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/RoodrigoRoot",
                "html_url": "https://github.com/RoodrigoRoot",
                "followers_url": "https://api.github.com/users/RoodrigoRoot/followers",
                "following_url": "https://api.github.com/users/RoodrigoRoot/following{/other_user}",
                "gists_url": "https://api.github.com/users/RoodrigoRoot/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/RoodrigoRoot/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/RoodrigoRoot/subscriptions",
                "organizations_url": "https://api.github.com/users/RoodrigoRoot/orgs",
                "repos_url": "https://api.github.com/users/RoodrigoRoot/repos",
                "events_url": "https://api.github.com/users/RoodrigoRoot/events{/privacy}",
                "received_events_url": "https://api.github.com/users/RoodrigoRoot/received_events",
                "type": "User",
                "site_admin": False
            },
            "repo": {
                "id": 491270000,
                "node_id": "R_kgDOHUgvcA",
                "name": "flat-backend-test",
                "full_name": "RoodrigoRoot/flat-backend-test",
                "private": False,
                "owner": {
                    "login": "RoodrigoRoot",
                    "id": 50676016,
                    "node_id": "MDQ6VXNlcjUwNjc2MDE2",
                    "avatar_url": "https://avatars.githubusercontent.com/u/50676016?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/RoodrigoRoot",
                    "html_url": "https://github.com/RoodrigoRoot",
                    "followers_url": "https://api.github.com/users/RoodrigoRoot/followers",
                    "following_url": "https://api.github.com/users/RoodrigoRoot/following{/other_user}",
                    "gists_url": "https://api.github.com/users/RoodrigoRoot/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/RoodrigoRoot/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/RoodrigoRoot/subscriptions",
                    "organizations_url": "https://api.github.com/users/RoodrigoRoot/orgs",
                    "repos_url": "https://api.github.com/users/RoodrigoRoot/repos",
                    "events_url": "https://api.github.com/users/RoodrigoRoot/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/RoodrigoRoot/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "html_url": "https://github.com/RoodrigoRoot/flat-backend-test",
                "description": None,
                "fork": False,
                "url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test",
                "forks_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/forks",
                "keys_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/collaborators{/collaborator}",
                "teams_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/teams",
                "hooks_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/hooks",
                "issue_events_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/events{/number}",
                "events_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/events",
                "assignees_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/assignees{/user}",
                "branches_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/branches{/branch}",
                "tags_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/tags",
                "blobs_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/languages",
                "stargazers_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/stargazers",
                "contributors_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/contributors",
                "subscribers_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/subscribers",
                "subscription_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/subscription",
                "commits_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/comments{/number}",
                "contents_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/contents/{+path}",
                "compare_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/merges",
                "archive_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/downloads",
                "issues_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues{/number}",
                "pulls_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/labels{/name}",
                "releases_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/releases{/id}",
                "deployments_url": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/deployments",
                "created_at": "2022-05-11T20:57:39Z",
                "updated_at": "2022-05-12T13:56:05Z",
                "pushed_at": "2022-05-16T06:01:28Z",
                "git_url": "git://github.com/RoodrigoRoot/flat-backend-test.git",
                "ssh_url": "git@github.com:RoodrigoRoot/flat-backend-test.git",
                "clone_url": "https://github.com/RoodrigoRoot/flat-backend-test.git",
                "svn_url": "https://github.com/RoodrigoRoot/flat-backend-test",
                "homepage": None,
                "size": 26,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": "Python",
                "has_issues": True,
                "has_projects": True,
                "has_downloads": True,
                "has_wiki": True,
                "has_pages": False,
                "forks_count": 0,
                "mirror_url": None,
                "archived": False,
                "disabled": False,
                "open_issues_count": 0,
                "license": None,
                "allow_forking": True,
                "is_template": False,
                "topics": [],
                "visibility": "public",
                "forks": 0,
                "open_issues": 0,
                "watchers": 0,
                "default_branch": "main"
            }
        },
        "_links": {
            "self": {
                "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/46"
            },
            "html": {
                "href": "https://github.com/RoodrigoRoot/flat-backend-test/pull/46"
            },
            "issue": {
                "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/46"
            },
            "comments": {
                "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/issues/46/comments"
            },
            "review_comments": {
                "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/46/comments"
            },
            "review_comment": {
                "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/comments{/number}"
            },
            "commits": {
                "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/pulls/46/commits"
            },
            "statuses": {
                "href": "https://api.github.com/repos/RoodrigoRoot/flat-backend-test/statuses/b5c5b678aad30675bc5ca22d02b7a62ca9d202c8"
            }
        },
        "author_association": "OWNER",
        "auto_merge": None,
        "active_lock_reason": None,
        "merged": False,
        "mergeable": True,
        "rebaseable": False,
        "mergeable_state": "clean",
        "merged_by": None,
        "comments": 0,
        "review_comments": 0,
        "maintainer_can_modify": False,
        "commits": 1,
        "additions": 0,
        "deletions": 0,
        "changed_files": 1
    }
    }

    return data


@pytest.fixture
def mock_response_pull_status_open():
    data = {'success': True, 'data':{
        "url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/pulls/1347",
        "id": 1,
        "node_id": "MDExOlB1bGxSZXF1ZXN0MQ==",
        "html_url": "https://github.com/roodrigoroot/flat-backend-test/pull/1347",
        "diff_url": "https://github.com/roodrigoroot/flat-backend-test/pull/1347.diff",
        "patch_url": "https://github.com/roodrigoroot/flat-backend-test/pull/1347.patch",
        "issue_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/issues/1347",
        "commits_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/pulls/1347/commits",
        "review_comments_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/pulls/1347/comments",
        "review_comment_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/pulls/comments{/number}",
        "comments_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/issues/1347/comments",
        "statuses_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e",
        "number": 1347,
        "state": "open",
        "locked": True,
        "title": "Pull request de prueba",
        "user": {
            "login": "roodrigoroot",
            "id": 1,
            "node_id": "MDQ6VXNlcjE=",
            "avatar_url": "https://github.com/images/error/roodrigoroot_happy.gif",
            "gravatar_id": "",
            "url": "https://api.github.com/users/roodrigoroot",
            "html_url": "https://github.com/roodrigoroot",
            "followers_url": "https://api.github.com/users/roodrigoroot/followers",
            "following_url": "https://api.github.com/users/roodrigoroot/following{/other_user}",
            "gists_url": "https://api.github.com/users/roodrigoroot/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/roodrigoroot/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/roodrigoroot/subscriptions",
            "organizations_url": "https://api.github.com/users/roodrigoroot/orgs",
            "repos_url": "https://api.github.com/users/roodrigoroot/repos",
            "events_url": "https://api.github.com/users/roodrigoroot/events{/privacy}",
            "received_events_url": "https://api.github.com/users/roodrigoroot/received_events",
            "type": "User",
            "site_admin": False
        },
        "body": "Please pull these awesome changes in!",
        "labels": [
            {
                "id": 208045946,
                "node_id": "MDU6TGFiZWwyMDgwNDU5NDY=",
                "url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/labels/bug",
                "name": "bug",
                "description": "Something isn't working",
                "color": "f29513",
                "default": True
            }
        ],
        "milestone": {
            "url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/milestones/1",
            "html_url": "https://github.com/roodrigoroot/flat-backend-test/milestones/v1.0",
            "labels_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/milestones/1/labels",
            "id": 1002604,
            "node_id": "MDk6TWlsZXN0b25lMTAwMjYwNA==",
            "number": 1,
            "state": "open",
            "title": "v1.0",
            "description": "Tracking milestone for version 1.0",
            "creator": {
                "login": "roodrigoroot",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "avatar_url": "https://github.com/images/error/roodrigoroot_happy.gif",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roodrigoroot",
                "html_url": "https://github.com/roodrigoroot",
                "followers_url": "https://api.github.com/users/roodrigoroot/followers",
                "following_url": "https://api.github.com/users/roodrigoroot/following{/other_user}",
                "gists_url": "https://api.github.com/users/roodrigoroot/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roodrigoroot/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roodrigoroot/subscriptions",
                "organizations_url": "https://api.github.com/users/roodrigoroot/orgs",
                "repos_url": "https://api.github.com/users/roodrigoroot/repos",
                "events_url": "https://api.github.com/users/roodrigoroot/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roodrigoroot/received_events",
                "type": "User",
                "site_admin": False
            },
            "open_issues": 4,
            "closed_issues": 8,
            "created_at": "2011-04-10T20:09:31Z",
            "updated_at": "2014-03-03T18:58:10Z",
            "closed_at": "2013-02-12T13:22:01Z",
            "due_on": "2012-10-09T23:39:01Z"
        },
        "active_lock_reason": "too heated",
        "created_at": "2011-01-26T19:01:12Z",
        "updated_at": "2011-01-26T19:01:12Z",
        "closed_at": "2011-01-26T19:01:12Z",
        "merged_at": "2011-01-26T19:01:12Z",
        "merge_commit_sha": "e5bd3914e2e596debea16f433f57875b5b90bcd6",
        "assignee": {
            "login": "roodrigoroot",
            "id": 1,
            "node_id": "MDQ6VXNlcjE=",
            "avatar_url": "https://github.com/images/error/roodrigoroot_happy.gif",
            "gravatar_id": "",
            "url": "https://api.github.com/users/roodrigoroot",
            "html_url": "https://github.com/roodrigoroot",
            "followers_url": "https://api.github.com/users/roodrigoroot/followers",
            "following_url": "https://api.github.com/users/roodrigoroot/following{/other_user}",
            "gists_url": "https://api.github.com/users/roodrigoroot/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/roodrigoroot/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/roodrigoroot/subscriptions",
            "organizations_url": "https://api.github.com/users/roodrigoroot/orgs",
            "repos_url": "https://api.github.com/users/roodrigoroot/repos",
            "events_url": "https://api.github.com/users/roodrigoroot/events{/privacy}",
            "received_events_url": "https://api.github.com/users/roodrigoroot/received_events",
            "type": "User",
            "site_admin": False
        },
        "assignees": [
            {
                "login": "roodrigoroot",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "avatar_url": "https://github.com/images/error/roodrigoroot_happy.gif",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roodrigoroot",
                "html_url": "https://github.com/roodrigoroot",
                "followers_url": "https://api.github.com/users/roodrigoroot/followers",
                "following_url": "https://api.github.com/users/roodrigoroot/following{/other_user}",
                "gists_url": "https://api.github.com/users/roodrigoroot/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roodrigoroot/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roodrigoroot/subscriptions",
                "organizations_url": "https://api.github.com/users/roodrigoroot/orgs",
                "repos_url": "https://api.github.com/users/roodrigoroot/repos",
                "events_url": "https://api.github.com/users/roodrigoroot/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roodrigoroot/received_events",
                "type": "User",
                "site_admin": False
            },
            {
                "login": "hubot",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "avatar_url": "https://github.com/images/error/hubot_happy.gif",
                "gravatar_id": "",
                "url": "https://api.github.com/users/hubot",
                "html_url": "https://github.com/hubot",
                "followers_url": "https://api.github.com/users/hubot/followers",
                "following_url": "https://api.github.com/users/hubot/following{/other_user}",
                "gists_url": "https://api.github.com/users/hubot/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/hubot/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/hubot/subscriptions",
                "organizations_url": "https://api.github.com/users/hubot/orgs",
                "repos_url": "https://api.github.com/users/hubot/repos",
                "events_url": "https://api.github.com/users/hubot/events{/privacy}",
                "received_events_url": "https://api.github.com/users/hubot/received_events",
                "type": "User",
                "site_admin": True
            }
        ],
        "requested_reviewers": [
            {
                "login": "other_user",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "avatar_url": "https://github.com/images/error/other_user_happy.gif",
                "gravatar_id": "",
                "url": "https://api.github.com/users/other_user",
                "html_url": "https://github.com/other_user",
                "followers_url": "https://api.github.com/users/other_user/followers",
                "following_url": "https://api.github.com/users/other_user/following{/other_user}",
                "gists_url": "https://api.github.com/users/other_user/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/other_user/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/other_user/subscriptions",
                "organizations_url": "https://api.github.com/users/other_user/orgs",
                "repos_url": "https://api.github.com/users/other_user/repos",
                "events_url": "https://api.github.com/users/other_user/events{/privacy}",
                "received_events_url": "https://api.github.com/users/other_user/received_events",
                "type": "User",
                "site_admin": False
            }
        ],
        "requested_teams": [
            {
                "id": 1,
                "node_id": "MDQ6VGVhbTE=",
                "url": "https://api.github.com/teams/1",
                "html_url": "https://github.com/orgs/github/teams/justice-league",
                "name": "Justice League",
                "slug": "justice-league",
                "description": "A great team.",
                "privacy": "closed",
                "permission": "admin",
                "members_url": "https://api.github.com/teams/1/members{/member}",
                "repositories_url": "https://api.github.com/teams/1/repos"
            }
        ],
        "head": {
            "label": "roodrigoroot:new-topic",
            "ref": "new-topic",
            "sha": "6dcb09b5b57875f334f61aebed695e2e4193db5e",
            "user": {
                "login": "roodrigoroot",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "avatar_url": "https://github.com/images/error/roodrigoroot_happy.gif",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roodrigoroot",
                "html_url": "https://github.com/roodrigoroot",
                "followers_url": "https://api.github.com/users/roodrigoroot/followers",
                "following_url": "https://api.github.com/users/roodrigoroot/following{/other_user}",
                "gists_url": "https://api.github.com/users/roodrigoroot/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roodrigoroot/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roodrigoroot/subscriptions",
                "organizations_url": "https://api.github.com/users/roodrigoroot/orgs",
                "repos_url": "https://api.github.com/users/roodrigoroot/repos",
                "events_url": "https://api.github.com/users/roodrigoroot/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roodrigoroot/received_events",
                "type": "User",
                "site_admin": False
            },
            "repo": {
                "id": 1296269,
                "node_id": "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
                "name": "flat-backend-test",
                "full_name": "roodrigoroot/flat-backend-test",
                "owner": {
                    "login": "roodrigoroot",
                    "id": 1,
                    "node_id": "MDQ6VXNlcjE=",
                    "avatar_url": "https://github.com/images/error/roodrigoroot_happy.gif",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/roodrigoroot",
                    "html_url": "https://github.com/roodrigoroot",
                    "followers_url": "https://api.github.com/users/roodrigoroot/followers",
                    "following_url": "https://api.github.com/users/roodrigoroot/following{/other_user}",
                    "gists_url": "https://api.github.com/users/roodrigoroot/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/roodrigoroot/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/roodrigoroot/subscriptions",
                    "organizations_url": "https://api.github.com/users/roodrigoroot/orgs",
                    "repos_url": "https://api.github.com/users/roodrigoroot/repos",
                    "events_url": "https://api.github.com/users/roodrigoroot/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/roodrigoroot/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "private": False,
                "html_url": "https://github.com/roodrigoroot/flat-backend-test",
                "description": "This your first repo!",
                "fork": False,
                "url": "https://api.github.com/repos/roodrigoroot/flat-backend-test",
                "archive_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/{archive_format}{/ref}",
                "assignees_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/assignees{/user}",
                "blobs_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/git/blobs{/sha}",
                "branches_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/branches{/branch}",
                "collaborators_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/collaborators{/collaborator}",
                "comments_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/comments{/number}",
                "commits_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/commits{/sha}",
                "compare_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/compare/{base}...{head}",
                "contents_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/contents/{+path}",
                "contributors_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/contributors",
                "deployments_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/deployments",
                "downloads_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/downloads",
                "events_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/events",
                "forks_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/forks",
                "git_commits_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/git/commits{/sha}",
                "git_refs_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/git/refs{/sha}",
                "git_tags_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/git/tags{/sha}",
                "git_url": "git:github.com/roodrigoroot/flat-backend-test.git",
                "issue_comment_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/issues/comments{/number}",
                "issue_events_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/issues/events{/number}",
                "issues_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/issues{/number}",
                "keys_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/keys{/key_id}",
                "labels_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/labels{/name}",
                "languages_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/languages",
                "merges_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/merges",
                "milestones_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/notifications{?since,all,participating}",
                "pulls_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/pulls{/number}",
                "releases_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/releases{/id}",
                "ssh_url": "git@github.com:roodrigoroot/flat-backend-test.git",
                "stargazers_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/stargazers",
                "statuses_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/statuses/{sha}",
                "subscribers_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/subscribers",
                "subscription_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/subscription",
                "tags_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/tags",
                "teams_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/teams",
                "trees_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/git/trees{/sha}",
                "clone_url": "https://github.com/roodrigoroot/flat-backend-test.git",
                "mirror_url": "git:git.example.com/roodrigoroot/flat-backend-test",
                "hooks_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/hooks",
                "svn_url": "https://svn.github.com/roodrigoroot/flat-backend-test",
                "homepage": "https://github.com",
                "language": None,
                "forks_count": 9,
                "stargazers_count": 80,
                "watchers_count": 80,
                "size": 108,
                "default_branch": "master",
                "open_issues_count": 0,
                "topics": [
                    "roodrigoroot",
                    "atom",
                    "electron",
                    "api"
                ],
                "has_issues": True,
                "has_projects": True,
                "has_wiki": True,
                "has_pages": False,
                "has_downloads": True,
                "archived": False,
                "disabled": False,
                "pushed_at": "2011-01-26T19:06:43Z",
                "created_at": "2011-01-26T19:01:12Z",
                "updated_at": "2011-01-26T19:14:43Z",
                "permissions": {
                    "admin": False,
                    "push": False,
                    "pull": True
                },
                "allow_rebase_merge": True,
                "temp_clone_token": "ABTLWHOULUVAXGTRYU7OC2876QJ2O",
                "allow_squash_merge": True,
                "allow_merge_commit": True,
                "allow_forking": True,
                "forks": 123,
                "open_issues": 123,
                "license": {
                    "key": "mit",
                    "name": "MIT License",
                    "url": "https://api.github.com/licenses/mit",
                    "spdx_id": "MIT",
                    "node_id": "MDc6TGljZW5zZW1pdA=="
                },
                "watchers": 123
            }
        },
        "base": {
            "label": "roodrigoroot:master",
            "ref": "master",
            "sha": "6dcb09b5b57875f334f61aebed695e2e4193db5e",
            "user": {
                "login": "roodrigoroot",
                "id": 1,
                "node_id": "MDQ6VXNlcjE=",
                "avatar_url": "https://github.com/images/error/roodrigoroot_happy.gif",
                "gravatar_id": "",
                "url": "https://api.github.com/users/roodrigoroot",
                "html_url": "https://github.com/roodrigoroot",
                "followers_url": "https://api.github.com/users/roodrigoroot/followers",
                "following_url": "https://api.github.com/users/roodrigoroot/following{/other_user}",
                "gists_url": "https://api.github.com/users/roodrigoroot/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/roodrigoroot/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/roodrigoroot/subscriptions",
                "organizations_url": "https://api.github.com/users/roodrigoroot/orgs",
                "repos_url": "https://api.github.com/users/roodrigoroot/repos",
                "events_url": "https://api.github.com/users/roodrigoroot/events{/privacy}",
                "received_events_url": "https://api.github.com/users/roodrigoroot/received_events",
                "type": "User",
                "site_admin": False
            },
            "repo": {
                "id": 1296269,
                "node_id": "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
                "name": "flat-backend-test",
                "full_name": "roodrigoroot/flat-backend-test",
                "owner": {
                    "login": "roodrigoroot",
                    "id": 1,
                    "node_id": "MDQ6VXNlcjE=",
                    "avatar_url": "https://github.com/images/error/roodrigoroot_happy.gif",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/roodrigoroot",
                    "html_url": "https://github.com/roodrigoroot",
                    "followers_url": "https://api.github.com/users/roodrigoroot/followers",
                    "following_url": "https://api.github.com/users/roodrigoroot/following{/other_user}",
                    "gists_url": "https://api.github.com/users/roodrigoroot/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/roodrigoroot/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/roodrigoroot/subscriptions",
                    "organizations_url": "https://api.github.com/users/roodrigoroot/orgs",
                    "repos_url": "https://api.github.com/users/roodrigoroot/repos",
                    "events_url": "https://api.github.com/users/roodrigoroot/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/roodrigoroot/received_events",
                    "type": "User",
                    "site_admin": False
                },
                "private": False,
                "html_url": "https://github.com/roodrigoroot/flat-backend-test",
                "description": "This your first repo!",
                "fork": False,
                "url": "https://api.github.com/repos/roodrigoroot/flat-backend-test",
                "archive_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/{archive_format}{/ref}",
                "assignees_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/assignees{/user}",
                "blobs_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/git/blobs{/sha}",
                "branches_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/branches{/branch}",
                "collaborators_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/collaborators{/collaborator}",
                "comments_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/comments{/number}",
                "commits_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/commits{/sha}",
                "compare_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/compare/{base}...{head}",
                "contents_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/contents/{+path}",
                "contributors_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/contributors",
                "deployments_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/deployments",
                "downloads_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/downloads",
                "events_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/events",
                "forks_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/forks",
                "git_commits_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/git/commits{/sha}",
                "git_refs_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/git/refs{/sha}",
                "git_tags_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/git/tags{/sha}",
                "git_url": "git:github.com/roodrigoroot/flat-backend-test.git",
                "issue_comment_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/issues/comments{/number}",
                "issue_events_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/issues/events{/number}",
                "issues_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/issues{/number}",
                "keys_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/keys{/key_id}",
                "labels_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/labels{/name}",
                "languages_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/languages",
                "merges_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/merges",
                "milestones_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/notifications{?since,all,participating}",
                "pulls_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/pulls{/number}",
                "releases_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/releases{/id}",
                "ssh_url": "git@github.com:roodrigoroot/flat-backend-test.git",
                "stargazers_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/stargazers",
                "statuses_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/statuses/{sha}",
                "subscribers_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/subscribers",
                "subscription_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/subscription",
                "tags_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/tags",
                "teams_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/teams",
                "trees_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/git/trees{/sha}",
                "clone_url": "https://github.com/roodrigoroot/flat-backend-test.git",
                "mirror_url": "git:git.example.com/roodrigoroot/flat-backend-test",
                "hooks_url": "https://api.github.com/repos/roodrigoroot/flat-backend-test/hooks",
                "svn_url": "https://svn.github.com/roodrigoroot/flat-backend-test",
                "homepage": "https://github.com",
                "language": None,
                "forks_count": 9,
                "stargazers_count": 80,
                "watchers_count": 80,
                "size": 108,
                "default_branch": "master",
                "open_issues_count": 0,
                "topics": [
                    "roodrigoroot",
                    "atom",
                    "electron",
                    "api"
                ],
                "has_issues": True,
                "has_projects": True,
                "has_wiki": True,
                "has_pages": False,
                "has_downloads": True,
                "archived": False,
                "disabled": False,
                "pushed_at": "2011-01-26T19:06:43Z",
                "created_at": "2011-01-26T19:01:12Z",
                "updated_at": "2011-01-26T19:14:43Z",
                "permissions": {
                    "admin": False,
                    "push": False,
                    "pull": True
                },
                "allow_rebase_merge": True,
                "temp_clone_token": "ABTLWHOULUVAXGTRYU7OC2876QJ2O",
                "allow_squash_merge": True,
                "allow_merge_commit": True,
                "forks": 123,
                "open_issues": 123,
                "license": {
                    "key": "mit",
                    "name": "MIT License",
                    "url": "https://api.github.com/licenses/mit",
                    "spdx_id": "MIT",
                    "node_id": "MDc6TGljZW5zZW1pdA=="
                },
                "watchers": 123
            }
        },
        "_links": {
            "self": {
                "href": "https://api.github.com/repos/roodrigoroot/flat-backend-test/pulls/1347"
            },
            "html": {
                "href": "https://github.com/roodrigoroot/flat-backend-test/pull/1347"
            },
            "issue": {
                "href": "https://api.github.com/repos/roodrigoroot/flat-backend-test/issues/1347"
            },
            "comments": {
                "href": "https://api.github.com/repos/roodrigoroot/flat-backend-test/issues/1347/comments"
            },
            "review_comments": {
                "href": "https://api.github.com/repos/roodrigoroot/flat-backend-test/pulls/1347/comments"
            },
            "review_comment": {
                "href": "https://api.github.com/repos/roodrigoroot/flat-backend-test/pulls/comments{/number}"
            },
            "commits": {
                "href": "https://api.github.com/repos/roodrigoroot/flat-backend-test/pulls/1347/commits"
            },
            "statuses": {
                "href": "https://api.github.com/repos/roodrigoroot/flat-backend-test/statuses/6dcb09b5b57875f334f61aebed695e2e4193db5e"
            }
        },
        "author_association": "OWNER",
        "auto_merge": None,
        "draft": False,
        "merged": False,
        "mergeable": True,
        "rebaseable": True,
        "mergeable_state": "clean",
        "merged_by": {
            "login": "roodrigoroot",
            "id": 1,
            "node_id": "MDQ6VXNlcjE=",
            "avatar_url": "https://github.com/images/error/roodrigoroot_happy.gif",
            "gravatar_id": "",
            "url": "https://api.github.com/users/roodrigoroot",
            "html_url": "https://github.com/roodrigoroot",
            "followers_url": "https://api.github.com/users/roodrigoroot/followers",
            "following_url": "https://api.github.com/users/roodrigoroot/following{/other_user}",
            "gists_url": "https://api.github.com/users/roodrigoroot/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/roodrigoroot/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/roodrigoroot/subscriptions",
            "organizations_url": "https://api.github.com/users/roodrigoroot/orgs",
            "repos_url": "https://api.github.com/users/roodrigoroot/repos",
            "events_url": "https://api.github.com/users/roodrigoroot/events{/privacy}",
            "received_events_url": "https://api.github.com/users/roodrigoroot/received_events",
            "type": "User",
            "site_admin": False
        },
        "comments": 10,
        "review_comments": 0,
        "maintainer_can_modify": True,
        "commits": 3,
        "additions": 100,
        "deletions": 3,
        "changed_files": 5
    }}
    return data


@pytest.fixture
def mock_response_pull_status_merge():
    data = {'success': True, 'data':{
        "sha": "6dcb09b5b57875f334f61aebed695e2e4193db5e",
        "merged": True,
        "message": "Pull Request successfully merged"
    }}
    return data

@pytest.fixture
def mock_create_pull_status_open():
    data = {
        "title": "Pull request de prueba",
        "description": "Este Pull es solo una prueba de creación desde otra API",
        "status": "open"
    }
    return data


@pytest.fixture
def mock_create_pull_status_merge():
    data = {
        "title": "Pull request de prueba",
        "description": "Este Pull es solo una prueba de creación desde otra API",
        "status": "merge"
    }
    return data
